# Base configs
baseurl: "/photo"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Chipio"
subtitle: "See the world through my eyes!"
author: "Chipio"
header:
 title: "Photography"
 subtitle: "by chipiofur"
footer:
 name: "Hey there, my name is Chip."
 bio: "I travel to a bunch of conventions and take photos of my friends around the con space. Enjoy!"
 furtrack: "You can see the rest of my photo catalog on <a href='https://www.furtrack.com/index/photographer:chipiofur'>Furtrack</a>."
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/chipiofur"
  furtrack: "https://www.furtrack.com/index/photographer:chipiofur"
  telegram: "https://t.me/chipiofur"
  github: "https://www.github.com/ChipioIndustries"
